#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
killall picom; picom  &

# Terminate already running bar instances
killall polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# Launch polybar
$HOME/.config/polybar/launch.sh


feh  --bg-fill ~/Downloads/wallpaper.jpg

bspc monitor -d I II III IV VI VII VIII IX 
bspc config border_width         2
bspc config window_gap           15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true 

# Set the border colors.
bspc config normal_border_color \#31748f
bspc config active_border_color 
bspc config focused_border_color \#9ccfd8
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color6"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"
xset -dpms s off



